---
-
    hosts: all
    vars_files:
        - vars/main.yml
        - vars/vhosts.yml
    vars:
        # remove the 000-default apache site.
        apache_remove_default_vhost: true
        mysql_root_password: root
        php_packages:
            # you can use mod_php for apache or php-fpm (https://galaxy.ansible.com/geerlingguy/php/#readme)
            - libapache2-mod-php
    roles:
        # make sure these roles have been added to requirements.yml so they'll be automatically installed.
        - geerlingguy.apache
        - geerlingguy.php
        - geerlingguy.mysql
        - geerlingguy.php-mysql
    become: true
    tasks:
        -
            name: remove the default /var/www/html folder
            file:
                path: /var/www/html
                state: absent
            become: true
            
        -
            # (the apache vhosts are defined in vars/vhosts.yml)
            name: create web root folders for the apache vhosts
            file:
                path: "{{ item['documentroot'] }}"
                state: directory
            with_items: "{{ apache_vhosts }}"
            when: item['documentroot'] is defined
            
        -
            name: chown the web root to the www-data group
            file:
                path: /var/www
                state: directory
                group: www-data
                mode: 0775
                recurse: true
            become: true
...
